default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: demoapp
  username: postgres
  password: 123456
  host: localhost
  port: 5432

development:
  <<: *default

dev:
  <<: *default
  host: 202.164.34.20
  username: demoapp
  password: 123456

staging:
  <<: *default
  host: localhost
  username: demoapp
  password: 123456

production:
  <<: *default
  host: localhost
  database: demoapp
  username: demoapp
  password: 123456
